"""helpmegodpt2

Revision ID: 1be7aa8cc0e3
Revises: aa1452a5a206
Create Date: 2026-02-18 10:12:28.128167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be7aa8cc0e3'
down_revision: Union[str, Sequence[str], None] = 'aa1452a5a206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
