"""helpmegod

Revision ID: 361e3778343a
Revises: 
Create Date: 2026-02-18 02:17:16.376288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361e3778343a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('servicos_catalogo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('complexidade_ust', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['servicos_catalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_contrato', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('valor_ust', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_contrato')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_orcamento', sa.String(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('versao', sa.String(), nullable=True),
    sa.Column('valor_total_bruto', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('desconto_percentual', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('valor_total_liquido', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_orcamento')
    )
    op.create_table('itens_orcamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('atividade_id', sa.Integer(), nullable=False),
    sa.Column('horas_estimadas', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('complexidade_snapshot', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('valor_ust_snapshot', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('sequencia', sa.Integer(), nullable=True),
    sa.Column('subtotal_ust', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('subtotal_bruto', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['atividade_id'], ['servicos_catalogo.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_alteracao', sa.String(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('item_orcamento_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('valor_anterior', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('valor_novo', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('data_alteracao', sa.String(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_orcamento_id'], ['itens_orcamento.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_auditoria')
    op.drop_table('itens_orcamento')
    op.drop_table('orcamentos')
    op.drop_table('projetos')
    op.drop_table('contratos')
    op.drop_table('usuarios')
    op.drop_table('servicos_catalogo')
    op.drop_table('clientes')
    # ### end Alembic commands ###
